### PR TITLE
Add Munkireport-php

### PR DESCRIPTION
**Pull request by gmarnin**
Add Munkireport-php to the Management Tools section. - @gmarnin

### CODE REVIEW

**Comment by macadmininfo** [comment]
So...Munki is effectively its own ecosystem, and I’ve tried to avoid going down that rabbit hole. However...help me here...

It’s a good addition once someone has been introduced to Munki, so, it’s valuable. What does this look like?

Does Munki get its own section? A separate page altogether? I’m thinking this may be what happens with the meet ups at some point, so it isn’t out of the question. Is there some other way to handle this?

I had this (short) debate when asked to add the Munki-specific mailing lists, and I think it’s worth getting ahead of it sooner rather than later.

**Comment by gmarnin** [comment]
Good questions. 

The site advertises itself as `A resource for beginning and experienced Mac/Apple administrators.` So beginners want to find the big picture tools and the experienced admins will come looking for the smaller, lesser known tools that they may not know about. Ultimately, to be complete, all tools should get listed. Think of this site like the MacAdmins version of Tim's [python-macadmin-tools](https://github.com/timsutton/python-macadmin-tools) list. That's a focused, complete list of tools. 

In this cases, if you are running Munki then you want to also be running either [Sal](https://github.com/macadmininfo/macadmininfo.github.io/blob/master/index.html#L244) or Munkireport-php. I don't know what was your [thought process](https://github.com/macadmininfo/macadmininfo.github.io/pull/3#issuecomment-362051658) was for including Sal but certainly Munkireport-php should be next to Sal. 

How the site is designed may depend how big the topic gets. I don't think I would go with a separate page just yet. A separate section sound right for the bigger topics.

**Comment by danner26** [comment]
Agreed, MunkiReport-PHP should be added in my opinion, but maybe in another section that is broken out for MDM and reporting. Sorry for creating a new issue #25 before seeing this - go ahead and close that issue.

**Comment by macadmininfo** [comment]
Sorry this took so long...you're right, and now it's in.

**Pull request merged**
