### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by justinesgar**
Added ACEs Conference to conference list.

### CODE REVIEW

**Comment by justinesgar** [comment]
It’s not for business people as a whole - but IT Consultants, and specifically Apple consultants - hence it’s following.  Wouldn’t those people be considered “Mac Admins”?

Justin
-----------------
Justin T. Esgar
CEO/President
347-369-4878
virtuacomputers.com <http://www.virtuacomputers.com/>

Check out the book: Appitalize On Your Idea <http://www.amazon.com/dp/B00HMB8B6U>

**Comment by macadmininfo** [comment]
Having not been able to attend, I’m genuinely asking: what’s the content of the event? I understand it as business advice for people running their (Apple-focused) consulting business. The resources on this list are focused on the technical aspects of being a Mac/Apple admin.

Maybe it belongs under “jobs”? So, if you’re looking to strike out on your own? Or maybe the “Conferences” section needs subheadings?

I’m always fine with hearing that I’m being too pedantic, but Aces really is different than everything else here. So, just trying to figure out the right fit.

**Comment by justinesgar** [comment]
Yes it business advice and practices for the Apple Consultants. But it leans a little into technical when we start talking about tools such as Addigy or Watchman. 

I get what you are saying where your site is more technical focused, but to say these people or this conference isn’t for “MacAdmins” is I think where we get hung up. These people are still MacAdmins in my eyes. Just b/c you want to better yourself in a non-technical way doesn’t make you any less of an Admin. Maybe put ACEs up with an asterisk (like someone in the hall of fame who has beaten a record but there is just something small amiss)?

J
-----------------
Justin T. Esgar
CEO/President
347-369-4878
virtuacomputers.com <http://www.virtuacomputers.com/>

Check out the book: Appitalize On Your Idea <http://www.amazon.com/dp/B00HMB8B6U>

**Comment by macadmininfo** [comment]
They may be MacAdmins in some way, but in this *context*, they’re business owners. They’re attending Aces to improve their business acumen. Would that be fair to say?

**Comment by justinesgar** [comment]
Ed - 

Yes that would be a fair statement.

Justin
-----------------
Justin T. Esgar
CEO/President
347-369-4878
virtuacomputers.com <http://www.virtuacomputers.com/>

Check out the book: Appitalize On Your Idea <http://www.amazon.com/dp/B00HMB8B6U>

**Comment by macadmininfo** [comment]
OK - I handled this by adding “Technical” and “Business” sections to Conferences. Added Aces under “Business” Sorry for the delay.

**Comment by justinesgar** [comment]
Thanks so much Ed.

Much appreciated.

Justin
-----------------
Justin T. Esgar
CEO/President
347-369-4878
virtuacomputers.com <http://www.virtuacomputers.com/>

Check out the book: Appitalize On Your Idea <http://www.amazon.com/dp/B00HMB8B6U>

**Pull request closed without merging**
